name: CI/CD Workflow

# Dispara para Pull Requests em develop e master
on:
  push:
    branches:
      - develop
      - master
      - test_pipe

jobs:
  # Job de Testes: só roda quando o PR tiver base em 'develop'
  test:
#    if: github.event.pull_request.base.ref == 'test_pipe'
    runs-on: ubuntu-latest
    steps:
      # 1) Faz checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) (Exemplo) Configura ambiente Python (troque conforme sua stack)
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Instala dependências (ajuste para requirements.txt, package.json, pom.xml etc.)
      - name: Install dependencies
        run: |
          pip install django

      # 4) Executa suite de testes
      - name: Run tests
        run:
          echo "pytest ou npm test / mvn test / dotnet test, dependendo da sua stack"
