name: CI Develop

# Dispara em push ou PR para develop
on:
  push:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Executar testes unitários
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar migrações
        run: |
          python manage.py migrate

      - name: Executar testes
        run: |
          pytest -q

